#!/bin/bash
#
# Simple download manager that uses wget and a database to download files.
#
# Distributed under the GNU GPL v3
#

# parse config file
. ./sheget.conf

#
# Output download status in a clean and readable way
#
list() {
	echo -e "Download status (sorted by priority):"
	echo -e "\n# Error:"
	sqlite3 $DB_PATH "SELECT url FROM downloads WHERE complete==-1 ORDER BY
		priority DESC;"
	echo -e "\n# Complete:"
	sqlite3 $DB_PATH "SELECT url FROM downloads WHERE complete==1 ORDER BY
	            priority DESC;"
	echo -e "\n# Still queued:"
	sqlite3 $DB_PATH "SELECT url FROM downloads WHERE complete==0 ORDER BY
	            priority DESC;"
}

#
# MAIN
#
if [ "$1" = "-l" ]; then
	list
	exit
fi

while true
do
	
url=$(sqlite3 $DB_PATH "SELECT url FROM downloads WHERE complete==0 
	ORDER BY priority DESC LIMIT 1;")
if [ -z "$url" ]; then
	echo Nothing to do. Sleeping.
      	sleep $POLL_INTERVAL
else
     	
wget -c -P $DOWNLOAD_DIR --limit-rate=$MAX_RATE $url
      
if [ $? -ne 0 ]; then
	sqlite3 $DB_PATH "UPDATE downloads SET complete = -1 WHERE url=='$url';"else
	sqlite3 $DB_PATH "UPDATE downloads SET complete = 1 WHERE url=='$url';"
fi

fi
done
